---
- name: Enable systemd services
  become: true
  when: systemd_services is defined
  ansible.builtin.systemd:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
    scope: "{{ item.scope }}"
  with_items: "{{ systemd_services }}"
  tags:
    - services
