---
rpm_keys_import:
  - https://packages.microsoft.com/keys/microsoft.asc

rpm_repositories_create:
  - name: vscode
    description: Visual Studio Code Repository
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    file: vscode

rpm_repositories_enable:
  - google-chrome

rpm_packages:
  - tmux
  - fzf
  - xclip
  - git
  - zsh
  - google-chrome-stable
  - code
  - datovka
  - at
  - ffmpeg-free
  - python3-tracer
  - gimp
  - vim-enhanced
  - emacs
  - dconf-editor
  - nmap
  - '@Container Management'
  - '@virtualization'

flatpak_repos:
  - name: flathub
    url: https://flathub.org/repo/flathub.flatpakrepo

flatpak_packages:
  - io.podman_desktop.PodmanDesktop
  - org.gnome.Extensions
  - org.mozilla.Thunderbird
  - org.signal.Signal
  - org.telegram.desktop
  - org.videolan.VLC

systemd_services:
  - name: libvirtd
    state: started
    enabled: true
    scope: system
  - name: atd
    state: started
    enabled: true
    scope: system

gnome_dconf_settings:
  - key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"