---
- name: Import rpm keys
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop: "{{ rpm_keys_import }}"
  tags:
    - rpm

- name: Create RPM repositories
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    file: "{{ item.file | default(omit) }}"
  loop: "{{ rpm_repositories_create }}"
  tags:
    - rpm

- name: Enable third party RPM repositories
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled "{{ item }}"
    warn: false
  loop: "{{ rpm_repositories_enable }}"
  tags:
    - rpm
  changed_when: false

- name: Install RPM Packages
  ansible.builtin.dnf:
    name: "{{ rpm_packages }}"
    update_cache: true
    state: present
  tags:
    - rpm

- name: Add the flathub flatpak repository remote to the system installation
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    state: present
    flatpakrepo_url: "{{ item.url }}"
    method: system
  loop: "{{ flatpak_repos }}"
  tags:
    - flatpak

- name: Install flatpak packages
  community.general.packaging.os.flatpak:
    name: "{{ flatpak_packages }}"
    state: present
  retries: 3
  tags:
    - flatpak
