---
- name: Update dconf settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ gnome_dconf_settings }}"
  tags:
    - gnome

- name: Create tmux config
  ansible.builtin.copy:
    src: tmux.conf
    dest: /home/{{ ansible_user }}/.tmux.conf
    mode: "0644"
    owner: "{{ ansible_user }}"
