---
- name: Import rpm keys
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop: "{{ rpm_keys_import }}"
  tags:
    - rpm

## TODO
# sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
- name: Create RPM repositories
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    file: "{{ item.file | default(omit) }}"
  loop: "{{ rpm_repositories_create }}"
  tags:
    - rpm

- name: Install RPM Packages
  ansible.builtin.dnf:
    name: "{{ rpm_packages }}"
    update_cache: true
    state: present
  tags:
    - rpm

- name: Add the flathub flatpak repository remote to the system installation
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    state: present
    flatpakrepo_url: "{{ item.url }}"
    method: system
  loop: "{{ flatpak_repos }}"
  tags:
    - flatpak

- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ flatpak_packages }}"
    state: present
  retries: 3
  tags:
    - flatpak

- name: Install pip packages as user
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
    extra_args: --user
  loop: "{{ pip_packages }}"
