#SPDX-License-Identifier: MIT-0
---
# defaults file for fedora_desktop
gnome_terminal_profile_uuid: b1dcc9dd52624d8da863c897e6d979b9
gnome_terminal_profile_keys:
  - key: use-custom-command
    value: true
  - key: label
    value: "'tmux'"
  - key: custom-command
    value: "'tmux'"

kopia_restore: false

fedora_desktop_bashrc_filecontent: |
  # .bashrc

  # Source global definitions
  if [ -f /etc/bashrc ]; then
      . /etc/bashrc
  fi

  # User specific environment
  if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
      PATH="$HOME/.local/bin:$HOME/bin:$PATH"
  fi
  export PATH

  # Uncomment the following line if you don't like systemctl's auto-paging feature:
  # export SYSTEMD_PAGER=

  # User specific aliases and functions
  if [ -d ~/.bashrc.d ]; then
      for rc in ~/.bashrc.d/*; do
          if [ -f "$rc" ]; then
              . "$rc"
          fi
      done
  fi
  unset rc
