#SPDX-License-Identifier: MIT-0
---
# defaults file for fedora_desktop
gnome_terminal_profile_uuid: b1dcc9dd52624d8da863c897e6d979b9
gnome_terminal_profile_keys:
  - key: use-custom-command
    value: true
  - key: label
    value: "'tmux'"
  - key: custom-command
    value: "'tmux'"
