---
rpm_keys_import:
  - https://packages.microsoft.com/keys/microsoft.asc

rpm_repositories_create:
  - name: vscode
    description: Visual Studio Code Repository
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    file: vscode

rpm_repositories_enable:
  - google-chrome
  - copr:copr.fedorainfracloud.org:phracek:PyCharm
  - copr:copr.fedorainfracloud.org:atim:starship
  - rpmfusion-nonfree-nvidia-driver
  - rpmfusion-nonfree-steam

rpm_packages:
  - tmux
  - fzf
  - xclip
  - git
  - zsh
  - google-chrome-stable
  - code
  - datovka
  - at
  - ffmpeg-free
  - python3-tracer
  - python3-pip
  - gimp
  - vim-enhanced
  - emacs
  - dconf-editor
  - nmap
  - plantuml
  - graphviz
  - poppler-utils
  - myrepos
  - "@container-management"
  - "@virtualization"

flatpak_repos:
  - name: flathub
    url: https://flathub.org/repo/flathub.flatpakrepo

flatpak_packages:
  - io.podman_desktop.PodmanDesktop
  - org.gnome.Extensions
  - org.mozilla.Thunderbird
  - org.signal.Signal
  - org.telegram.desktop
  - org.videolan.VLC
  - com.synology.SynologyDrive
  - md.obsidian.Obsidian
  - com.slack.Slack
  - com.bitwarden.desktop

pip_packages:
  - djlint

systemd_services:
  - name: libvirtd
    state: started
    enabled: true
    scope: system
  - name: atd
    state: started
    enabled: true
    scope: system

gnome_dconf_settings:
  - key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"

fedora_desktop_myrepos_conf: |
  [git/ansible_collections/jwerak/fedora]
  checkout = git clone 'git@github.com:jwerak/ansible-fedora.git' 'fedora'

  [git/ansible_collections/jwerak/fedora_iot]
  checkout = git clone 'git@github.com:jwerak/ansible_collection_fedora_iot.git' 'fedora_iot'

  [git/ansible_collections/jwerak/homelab]
  checkout = git clone 'git@github.com:jwerak/ansible_collection_homelab.git' 'homelab'

  [git/ansible-execution-environments]
  checkout = git clone 'git@github.com:jwerak/ansible-execution-environments.git' 'ansible-execution-environments'

  [git/ansible-fedora]
  checkout = git clone 'git@github.com:jwerak/ansible-fedora.git' 'ansible-fedora'

  [git/homelab]
  checkout = git clone 'git@github.com:jwerak/homelab.git' 'homelab'

  [git/homelab-iot]
  checkout = git clone 'git@github.com:jwerak/homelab-iot.git' 'homelab-iot'

  [git/vm-provisioner]
  checkout = git clone 'git@github.com:jwerak/vm-provisioner.git' 'vm-provisioner'
