---
- name: Setup Fedora machine
  hosts: '{{ target | default("all") }}'
  gather_facts: false
  become: true
  tasks:
    - name: Install apps
      ansible.builtin.import_role:
        name: jwerak.fedora.fedora_apps

- name: Setup User config on Fedora machine
  hosts: '{{target|default("all")}}'
  gather_facts: false
  tasks:
    - name: Configure Gnome
      ansible.builtin.import_role:
        name: jwerak.fedora.fedora_desktop

    - name: Configure SystemD user units
      ansible.builtin.import_role:
        name: jwerak.fedora.fedora_services
